controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - q1
      - q2
      - q3
      - q4
      - q5
      - q6
