joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  # Position Controllers ---------------------------------------
arm_position_controller:
  type: effort_controllers/JointPositionController
  joints:
    - q1
    - q2
    - q3
    - q4
    - q5
    - q6
  gains:
    q1: { p: 1000.0, i: 1.0, d: 100.0 }
    q2: { p: 1000.0, i: 1.0, d: 100.0 }
    q3: { p: 1000.0, i: 1.0, d: 100.0 }
    q4: { p: -100.0, i: -1.0, d: -10.0 }
    q5: { p: 100.0, i: 1.0, d: 10.0 }
    q6: { p: -100.0, i: -1.0, d: -10.0 }

